# Generated by Django 5.0.6 on 2024-08-18 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_product_cover_book'),
        ('orders', '0003_cart_created_cart_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price_per_book', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Price per Book')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_in_cart', to='goods.book', verbose_name='Book')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='orders.cart', verbose_name='Cart')),
            ],
        ),
    ]
