# Generated by Django 5.0.6 on 2024-08-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_bookincart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookincart',
            old_name='books',
            new_name='book',
        ),
    ]
