# Generated by Django 5.0.6 on 2024-08-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_product_cover_book'),
        ('orders', '0005_rename_books_bookincart_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_in_cart', to='goods.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='bookincart',
            name='price_per_book',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price per Book'),
        ),
    ]
