# Generated by Django 5.0.6 on 2024-09-01 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
        ('orders', '0006_alter_bookincart_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='orders.cart')),
                ('tel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telephone', to='acc.customerprofile')),
            ],
        ),
    ]
