# Generated by Django 5.0.6 on 2024-07-28 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('main_refs', '0003_rename_number_series_pocket_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to='product_covers/%Y/%m/%d/', verbose_name='Product cover'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('publication_date', models.DateField()),
                ('pages', models.IntegerField(default=0)),
                ('binding', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13)),
                ('weight', models.IntegerField(default=0)),
                ('age_restriction', models.IntegerField(default=0)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('rating', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='main_refs.author')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='main_refs.genre')),
                ('image_cover', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='goods.product')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishing_house', to='main_refs.publishing_house')),
                ('series', models.ManyToManyField(to='main_refs.series')),
            ],
        ),
    ]
