# Generated by Django 5.0.6 on 2024-07-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_refs', '0002_publishing_house_series_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='number',
            new_name='pocket_book',
        ),
    ]
